name: Build and Release RC Signed APK
run-name: Build and Release RC Signed APK
on: workflow_dispatch
jobs:
  # Build debug (RC) APK
  build_debug_apk:
    uses: ./.github/workflows/build_signed_apk.yaml
    with:
      compile_type: debug

  # Release published RC APK
  release_rc:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "works"!

